### ISSUE TITLE
Let's use glue::glue() to construct strings

### ISSUE THREAD

**Issue by GegznaV** [nevrome/LanguageToolR#3]
Package `glue` provides with an elegant way to construct strings. E.g.:
 
```r
lang_tool_version <- 4.6
glue::glue("Current version: {lang_tool_version}")
```
results in:
```r
#> Current version: 4.6
```

Could `glue` be used internally in this package to construct strings of commands, file names, etc. as a replacement for, e.g., `paste()`? @nevrome What do you think?

**Comment by nevrome** [comment]
Hm. I mean... sure, you can replace every call to `paste()` with a call to `glue::glue()`. But what is the advantage? The syntax might be a bit more nice, but we also add another dependency. Do you think it's worth the effort?

I'm not against it. Just wondering.

**Comment by nevrome** [comment]
@GegznaV Can this issue be closed?
