### ISSUE TITLE
Use Travis CI

### ISSUE THREAD

**Issue by GegznaV** [nevrome/LanguageToolR#7]
Please, enable continuous integration service, such as [Travis CI](https://en.wikipedia.org/wiki/Travis_CI) (website: https://travis-ci.org), to carry out free automatic checking for the package. In this way, you could know if, e.g., a new pull request breaks the functionality of the package or everything is OK.

The quickest way to enable Travis CI is to use function `usethis::use_travis()` (link to [**usethis**](https://usethis.r-lib.org/)) in the project of this package. This function will create necessary setup files and will open websites, where you will have to sign in. And these actions should be performed by the owner of this GitHub repository.

**Comment by nevrome** [comment]
If we do this, I think we should [cache](https://docs.travis-ci.com/user/caching/#arbitrary-directories) the LanguageTool directory to avoid long build times and unnecessary traffic.

**Comment by nevrome** [comment]
Here we go!
