### ISSUE TITLE
Avoid function name clash (create a system and rename functions)

### ISSUE THREAD

**Issue by GegznaV** [nevrome/LanguageToolR#9]
There are functions/objects, that have the same names, e.g., `base::version` and `LanguageToolR::version()`. I think, this kind of issue should be avoided. So I suggest preceding all helper function names with, e.g., `lng_` (or a more appropriate prefix), and renaming to, e.g. `lng_get_version()`, `lng_test_setup()`, `lng_get_languages()` or `lng_list_languages()`.

@nevrome What is your opinion on this?

**Comment by nevrome** [comment]
Ja - that's a good idea. 

Maybe the prefix `lato_*` would work? The main function `languagetool()` could become `lato()`.

**Comment by GegznaV** [comment]
Prefix `lato_` is OK. But I'd prefer not to change the name of `languagetool()` to `lato()`.
